import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Link from 'next/link';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';

export default function myItems() {
  const products = [
    {
      name: 'Air Jordan',
      price: '$120.99',
      image: '/images/product-1.png',
      sold: true,
    },
    {
      name: 'Air Force',
      price: '$120.99',
      image: '/images/product-2.png',
      sold: false,
    },
    {
      name: 'Nike Air Max.',
      price: '$120.99',
      image: '/images/product-3.png',
      sold: true,
    },
    {
      name: 'Nike Air Yeezy',
      price: '$120.99',
      image: '/images/product-4.png',
      sold: false,
    },
    {
      name: 'Dunk',
      price: '$120.99',
      image: '/images/product-5.png',
      sold: false,
    },
    {
      name: 'Blazer',
      price: '$120.99',
      image: '/images/product-6.png',
      sold: false,
    },
  ];

  return (
    <div classNameName={styles.container}>
      <Head>
        <title>Hermes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
        />
      </Head>

      <Navbar />

      <section
        className="products"
        id="products"
        style={{ marginTop: '110px' }}
      >
        <h1 className="heading" style={{ marginBottom: '50px' }}>
          My <span>products</span>
        </h1>

        <div className="box-container">
          {products.map((p, index) => (
            <>
              <div className={`box`} key={`product ${index}`}>
                <img className="latestImage" src={p.image} alt="product" />
                <h3 className="alert">Sold</h3>
                <div className="content">
                  <h3>{p.name}</h3>
                  <div className="price">
                    {p.price} <span>$150.99</span>
                  </div>
                  <div className="stars">
                    <i className="fas fa-star"></i>
                    <i className="fas fa-star"></i>
                    <i className="fas fa-star"></i>
                    <i className="fas fa-star"></i>
                    <i className="far fa-star"></i>
                  </div>
                  <Link href="/checkout">
                    <a className="btn">Sell Now</a>
                  </Link>
                </div>
              </div>
            </>
          ))}
          {/* 
          <div className="box">
            <div className="icons">
              <a href="#" className="fas fa-heart"></a>
              <a href="#" className="fas fa-share"></a>
              <a href="#" className="fas fa-eye"></a>
            </div>
            <img src="/images/product-6.png" alt="" />
            <div className="content">
              <h3>nike shoes</h3>
              <div className="price">
                $120.99 <span>$150.99</span>
              </div>
              <div className="stars">
                <i className="fas fa-star"></i>
                <i className="fas fa-star"></i>
                <i className="fas fa-star"></i>
                <i className="fas fa-star"></i>
                <i className="far fa-star"></i>
              </div>
              <Link href="/checkout">
                <a className="btn">Buy Now</a>
              </Link>
            </div>
          </div> */}
        </div>
      </section>

      <Footer />
    </div>
  );
}
