import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Link from 'next/link';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';

export default function Home() {
  const products = [
    {
      name: 'Air Jordan',
      price: '$120.99',
      image: '/images/product-1.png',
      sold: true,
    },
    {
      name: 'Air Force',
      price: '$120.99',
      image: '/images/product-2.png',
      sold: false,
    },
    {
      name: 'Nike Air Max.',
      price: '$120.99',
      image: '/images/product-3.png',
      sold: true,
    },
    {
      name: 'Nike Air Yeezy',
      price: '$120.99',
      image: '/images/product-4.png',
      sold: false,
    },
    {
      name: 'Dunk',
      price: '$120.99',
      image: '/images/product-5.png',
      sold: false,
    },
    {
      name: 'Blazer',
      price: '$120.99',
      image: '/images/product-6.png',
      sold: false,
    },
  ];

  const featured = [
    {
      name: 'Air Jordan',
      price: '$120.99',
      image: '/images/product-1.png',
      description:
        'Lorem Ipsum Dolor Sit Amet Consectetur Adipisicing Elit. Dicta Facilis Praesentium Odit Voluptas Illum Iure Libero Quis Fuga Commodi. Autem',
      sold: true,
    },
    {
      name: 'Kyrie Infinity EP',
      price: '$120.99',
      image: '/images/f-img-1.1.png',
      description:
        'Lorem Ipsum Dolor Sit Amet Consectetur Adipisicing Elit. Dicta Facilis Praesentium Odit Voluptas Illum Iure Libero Quis Fuga Commodi. Autem',
      sold: false,
    },
    {
      name: 'Zion 2 PF',
      price: '$120.99',
      image: '/images/f-img-2.1.png',
      description:
        'Lorem Ipsum Dolor Sit Amet Consectetur Adipisicing Elit. Dicta Facilis Praesentium Odit Voluptas Illum Iure Libero Quis Fuga Commodi. Autem',
      sold: false,
    },
    {
      name: 'Air Jordan XXXVI Low',
      price: '$120.99',
      image: '/images/f-img-3.1.png',
      description:
        'Lorem Ipsum Dolor Sit Amet Consectetur Adipisicing Elit. Dicta Facilis Praesentium Odit Voluptas Illum Iure Libero Quis Fuga Commodi. Autem',
      sold: false,
    },
    {
      name: 'LeBron 16',
      price: '$120.99',
      image: '/images/f-img-1.1.png',
      description:
        'Lorem Ipsum Dolor Sit Amet Consectetur Adipisicing Elit. Dicta Facilis Praesentium Odit Voluptas Illum Iure Libero Quis Fuga Commodi. Autem',
      sold: false,
    },
  ];
  return (
    <div classNameName={styles.container}>
      <Head>
        <title>Hermes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
        />
      </Head>

      <Navbar />

      <section className="home" id="home">
        <div className="slide-container active">
          <div className="slide">
            <div className="content">
              <span>nike red shoes</span>
              <h3>nike metcon shoes</h3>
              <p>
                The world&apos;s best Online Sneaker Store. Buy your favorite
                Limited edition Shoes
              </p>
              <Link href="/checkout">
                <a className="btn">Buy Now</a>
              </Link>
            </div>
            <div className="image">
              <img src="/images/home-shoe-1.png" className="shoe" alt="" />
              <img src="/images/home-text-1.png" className="text" alt="" />
            </div>
          </div>
        </div>

        <div className="slide-container">
          <div className="slide">
            <div className="content">
              <span>nike blue shoes</span>
              <h3>nike metcon shoes</h3>
              <p>
                The world&apos;s best Online Sneaker Store. Buy your favorite
                Limited edition Shoes
              </p>
              <Link href="/checkout">
                <a className="btn">Buy Now</a>
              </Link>
            </div>
            <div className="image">
              <img src="/images/home-shoe-2.png" className="shoe" alt="" />
              <img src="/images/home-text-2.png" className="text" alt="" />
            </div>
          </div>
        </div>

        <div className="slide-container">
          <div className="slide">
            <div className="content">
              <span>nike yellow shoes</span>
              <h3>nike metcon shoes</h3>
              <p>
                The world&apos;s best Online Sneaker Store. Buy your favorite
                Limited edition Shoes
              </p>
              <Link href="/checkout">
                <a className="btn">Buy Now</a>
              </Link>
            </div>
            <div className="image">
              <img src="/images/home-shoe-3.png" className="shoe" alt="" />
              <img src="/images/home-text-3.png" className="text" alt="" />
            </div>
          </div>
        </div>

        {/* <div id="prev" className="fas fa-chevron-left" onClick="prev()"></div>
        <div id="next" className="fas fa-chevron-right" onClick="next()"></div> */}
      </section>

      <section className="service">
        <div className="box-container">
          <div className="box">
            <i className="fas fa-shipping-fast"></i>
            <h3>fast delivery</h3>
            <p>
              Lorem ipsum dolor sit, amet consectetur adipisicing elit. Illum,
              fugit.
            </p>
          </div>

          <div className="box">
            <i className="fas fa-undo"></i>
            <h3>10 days replacements</h3>
            <p>
              Lorem ipsum dolor sit, amet consectetur adipisicing elit. Illum,
              fugit.
            </p>
          </div>

          <div className="box">
            <i className="fas fa-headset"></i>
            <h3>24 x 7 support</h3>
            <p>
              Lorem ipsum dolor sit, amet consectetur adipisicing elit. Illum,
              fugit.
            </p>
          </div>
        </div>
      </section>

      <section className="products" id="products">
        <h1 className="heading">
          latest <span>products</span>
        </h1>

        <div className="box-container">
          {products.map((p, index) => (
            <>
              <div
                className={`box ${p.sold ? 'sold' : ''}`}
                key={`product ${index}`}
              >
                <img className="latestImage" src={p.image} alt="product" />
                <h3 className="alert">Sold</h3>
                <div className="content">
                  <h3>{p.name}</h3>
                  <div className="price">
                    {p.price} <span>$150.99</span>
                  </div>
                  <div className="stars">
                    <i className="fas fa-star"></i>
                    <i className="fas fa-star"></i>
                    <i className="fas fa-star"></i>
                    <i className="fas fa-star"></i>
                    <i className="far fa-star"></i>
                  </div>
                  <Link href="/checkout">
                    <a className="btn">Buy Now</a>
                  </Link>
                </div>
              </div>
            </>
          ))}
          {/* 
          <div className="box">
            <div className="icons">
              <a href="#" className="fas fa-heart"></a>
              <a href="#" className="fas fa-share"></a>
              <a href="#" className="fas fa-eye"></a>
            </div>
            <img src="/images/product-6.png" alt="" />
            <div className="content">
              <h3>nike shoes</h3>
              <div className="price">
                $120.99 <span>$150.99</span>
              </div>
              <div className="stars">
                <i className="fas fa-star"></i>
                <i className="fas fa-star"></i>
                <i className="fas fa-star"></i>
                <i className="fas fa-star"></i>
                <i className="far fa-star"></i>
              </div>
              <Link href="/checkout">
                <a className="btn">Buy Now</a>
              </Link>
            </div>
          </div> */}
        </div>
      </section>

      <section className="featured" id="featured">
        <h1 className="heading">
          <span>featured</span> products
        </h1>

        {featured.map((p, index) => (
          <>
            <div
              className={`row ${p.sold ? 'sold' : ''}`}
              key={`featured ${index}`}
            >
              <div className="image-container">
                <div className="big-image">
                  <img src={p.image} className="big-image-3" alt="" />
                </div>
                <h2 className={`alert ${p.sold ? 'sold' : ''}`}>Sold</h2>
              </div>
              <div className="content">
                <h3>{p.name}</h3>
                <div className="stars">
                  <i className="fas fa-star"></i>
                  <i className="fas fa-star"></i>
                  <i className="fas fa-star"></i>
                  <i className="fas fa-star"></i>
                  <i className="far fa-star"></i>
                </div>
                <p>{p.description}</p>
                <div className="price">
                  {p.price} <span>$120.99</span>
                </div>
                <Link href="/checkout">
                  <a className="btn">Buy Now</a>
                </Link>
              </div>
            </div>
          </>
        ))}
      </section>

      <section className="review" id="review">
        <h1 className="heading">
          customer&apos;s <span>review</span>
        </h1>

        <div className="box-container">
          <div className="box">
            <img src="/images/pic1.png" alt="" />
            <h3>john deo</h3>
            <p>
              Lorem ipsum, dolor sit amet consectetur adipisicing elit. Fugiat,
              quos eum. Laborum aut a consequatur ducimus, molestias possimus
              quisquam rerum temporibus ipsum voluptate accusamus, unde ab
              asperiores? Exercitationem, unde rem.
            </p>
            <div className="stars">
              <i className="fas fa-star"></i>
              <i className="fas fa-star"></i>
              <i className="fas fa-star"></i>
              <i className="fas fa-star"></i>
              <i className="far fa-star"></i>
            </div>
          </div>

          <div className="box">
            <img src="/images/pic2.png" alt="" />
            <h3>john deo</h3>
            <p>
              Lorem ipsum, dolor sit amet consectetur adipisicing elit. Fugiat,
              quos eum. Laborum aut a consequatur ducimus, molestias possimus
              quisquam rerum temporibus ipsum voluptate accusamus, unde ab
              asperiores? Exercitationem, unde rem.
            </p>
            <div className="stars">
              <i className="fas fa-star"></i>
              <i className="fas fa-star"></i>
              <i className="fas fa-star"></i>
              <i className="fas fa-star"></i>
              <i className="fas fa-star-half-alt"></i>
            </div>
          </div>

          <div className="box">
            <img src="/images/pic3.png" alt="" />
            <h3>john deo</h3>
            <p>
              Lorem ipsum, dolor sit amet consectetur adipisicing elit. Fugiat,
              quos eum. Laborum aut a consequatur ducimus, molestias possimus
              quisquam rerum temporibus ipsum voluptate accusamus, unde ab
              asperiores? Exercitationem, unde rem.
            </p>
            <div className="stars">
              <i className="fas fa-star"></i>
              <i className="fas fa-star"></i>
              <i className="fas fa-star"></i>
              <i className="fas fa-star"></i>
              <i className="fas fa-star"></i>
            </div>
          </div>
        </div>
      </section>

      <section className="newsletter">
        <div className="content">
          <h3>monthly newsletter</h3>
          <p>
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Earum
            ullam veniam at itaque culpa hic corporis saepe dicta doloremque
            nihil.
          </p>
          <form action="">
            <input
              type="email"
              placeholder="enter your email"
              className="box"
            />
            <input type="submit" value="send" className="btn" />
          </form>
        </div>
      </section>

      <Footer />
    </div>
  );
}
